environments:
  development:
    # tag::dataSources[]
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: ''
      dbCreate: update
      url: jdbc:mysql://localhost/tracking-main?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

    dataSources:
      tenant-1:
        url: "jdbc:mysql://localhost/tenant-1?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      tenant-2:
        url: "jdbc:mysql://localhost/tenant-2?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"

  # end::dataSources[]

  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: com.mysql.cj.jdbc.Driver
      username: bitsoft
      password: "bitSoft@123"
      dbCreate: update
      url: "jdbc:mysql://localhost/tracking-main?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 200
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

    dataSources:
      tenant-1:
        url: "jdbc:mysql://localhost/tenant-1?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      tenant-2:
      url: "jdbc:mysql://localhost/tenant-2?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
